### PR TITLE
The Web Optimization Project has optimized your repository!

### PR DESCRIPTION
**Pull request by devedse**
# Web Optimization Project (Beta)

The [Web Optimization Project](https://www.github.com/devedse/weboptimizationproject) is a project that will automatically optimizes files in git repositories by compressing them losslessly. This project was created by [Devedse](https://github.com/devedse) in an effort to save the world! :smirk:

If you have any questions, feel free to create an issue or join the gitter chat:
[Join the chat at https://gitter.im/WebOptimizationProject/Lobby](https://gitter.im/WebOptimizationProject/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

## Optimization

The Web Optimization Project optimized this repository. All optimizations (compressions) are done losslessly and no quality / data is lost. This is also verified afterwards by the Wop so you can be sure that your images are exactly the same.

### Commit 1

Information | Value
-- | --
Version | 0.0.2.0
Support file extension | .PNG .JPG .JPEG .GIF .BMP

#### Statistics

Stats | Value
-- | --
Total size before optimization | 24.6MB
Total size after optimization | 24.5MB
Optimized size compared to old | 99.5%
Total bytes saved | 126.4KB

#### Files optimized in this repository

FileName | Original Size | Optimized Size | Bytes Saved | Successful
-- | -- | -- | -- | --
attitude_rotation.png | 40.9KB | 21.3KB | 19.5KB | True
circle-horizontal.gif | 1021.2KB | 1021.2KB | 0B | True
circle-vertical.gif | 1.4MB | 1.4MB | 0B | True
cube-horizontal.gif | 2.2MB | 2.2MB | 0B | True
cube-vertical.gif | 3.2MB | 3.2MB | 0B | True
custom1.gif | 1.6MB | 1.6MB | 0B | True
custom2.gif | 400.2KB | 400.2KB | 0B | True
demo-circle-rotation.gif | 2MB | 2MB | 0B | True
demo-yaw-rotation.gif | 1.6MB | 1.6MB | 0B | True
logo.png | 615.9KB | 509KB | 106.9KB | True
pitch-horizontal.gif | 1.3MB | 1.3MB | 0B | True
pitch-vertical.gif | 1.4MB | 1.4MB | 0B | True
roll-horizontal.gif | 1.3MB | 1.3MB | 0B | True
roll-vertical.gif | 1.2MB | 1.2MB | 0B | True
scale-down.gif | 1.7MB | 1.7MB | 0B | True
scale-up.gif | 1.6MB | 1.6MB | 0B | True
yaw-horizontal.gif | 948.5KB | 948.5KB | 0B | True
yaw-vertical.gif | 1.1MB | 1.1MB | 0B | True

### CODE REVIEW

**Comment by shoheiyokoyama** [comment]
@devedse 
Thank you for your contribution to this project 👍

**Comment by devedse** [comment]
Woo :smile:. Any suggestions, ideas or other feedback?

**Comment by shoheiyokoyama** [comment]
@devedse 
Is gif supported?

**Comment by devedse** [comment]
In this version it works somewhat, but in the latest version it works better. I also implemented a gif comparer now to ensure that the input and output gifs are exactly the same (it compares all frames + delays in between frames).

I haven't done any runs with the latest version yet since for a very small number of images with a corrupt checksum it won't run the final validation, which means that even though the image was correctly optimized, it won't push it to the repository because it couldn't verify that it was optimized correctly:
https://github.com/SixLabors/ImageSharp/issues/290

If that's resolved, I will run the tool again :smile:.

**Comment by shoheiyokoyama** [comment]
@devedse
Thank you. 👍

**Pull request merged**
